package compiler

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"strings"
)

func Lower(program Program, sourcePath string, sourceRaw []byte) (SemanticIR, error) {
	if err := program.Validate(); err != nil {
		return SemanticIR{}, err
	}
	execution, err := Execute(program)
	if err != nil {
		return SemanticIR{}, err
	}
	canonical := program.canonical()
	ir := SemanticIR{
		Schema: IRSchema, ProgramID: canonical.ID, Dialect: canonical.Dialect, SourcePath: sourcePath,
		SourceDigest: DigestBytes(sourceRaw), Nodes: canonical.Nodes, Edges: canonical.Edges, Entry: canonical.Entry,
		TerminalReason: execution.TerminalReason, CapabilitySet: execution.CapabilitySet, EffectTrace: execution.EffectTrace,
	}
	ir.SemanticDigest = ir.canonicalDigest()
	return ir, nil
}

func Execute(program Program) (Execution, error) {
	if err := program.Validate(); err != nil {
		return Execution{}, err
	}
	nodes := map[string]Node{}
	for _, node := range program.Nodes {
		nodes[node.ID] = node
	}
	next := map[string][]string{}
	for _, edge := range program.Edges {
		next[edge.From] = append(next[edge.From], edge.To)
	}
	for key := range next {
		if len(next[key]) > 1 {
			return Execution{}, fmt.Errorf("execution is ambiguous at %s", key)
		}
	}
	visited := map[string]bool{}
	current := program.Entry
	result := Execution{EffectTrace: []string{}, CapabilitySet: []string{}, Path: []string{}}
	for steps := 0; steps <= len(nodes); steps++ {
		if visited[current] {
			return Execution{}, fmt.Errorf("execution contains a cycle at %s", current)
		}
		visited[current] = true
		node := nodes[current]
		result.Path = append(result.Path, current)
		result.EffectTrace = append(result.EffectTrace, node.Effects...)
		result.CapabilitySet = append(result.CapabilitySet, node.Capabilities...)
		outgoing := next[current]
		if len(outgoing) == 0 {
			result.TerminalReason = program.TerminalReason
			result.CapabilitySet = sortedUnique(result.CapabilitySet)
			return result, nil
		}
		current = outgoing[0]
	}
	return Execution{}, errors.New("execution exceeded node bound")
}

func RenderProgram(program Program, comment string) ([]byte, error) {
	if err := program.Validate(); err != nil {
		return nil, err
	}
	program = program.canonical()
	var out strings.Builder
	out.WriteString("gooo program v1\n")
	out.WriteString("program id=" + program.ID + " dialect=" + program.Dialect + " entry=" + program.Entry + "\n")
	if comment != "" {
		out.WriteString("# " + comment + "\n")
	}
	for _, node := range program.Nodes {
		out.WriteString("node id=" + node.ID + " symbol=" + node.Symbol + " capabilities=" + listValue(node.Capabilities) + " effects=" + listValue(node.Effects) + "\n")
	}
	for _, edge := range program.Edges {
		out.WriteString("edge id=" + edge.ID + " from=" + edge.From + " to=" + edge.To + "\n")
	}
	out.WriteString("terminal reason=" + program.TerminalReason + "\n")
	return []byte(out.String()), nil
}

func RenderIR(ir SemanticIR) ([]byte, error) {
	ir.SemanticDigest = ir.canonicalDigest()
	raw, err := json.MarshalIndent(ir, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(raw, '\n'), nil
}

func RenderPlan(plan MigrationPlan) ([]byte, error) {
	plan.PlanDigest = plan.canonicalDigest()
	raw, err := json.MarshalIndent(plan, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(raw, '\n'), nil
}

func RenderBinding(ir SemanticIR, packageName string) ([]byte, error) {
	raw, err := RenderIR(ir)
	if err != nil {
		return nil, err
	}
	metadata, err := json.Marshal(struct {
		Schema         string `json:"schema"`
		ProgramID      string `json:"program_id"`
		Dialect        string `json:"dialect"`
		SemanticDigest string `json:"semantic_digest"`
	}{BindingSchema, ir.ProgramID, ir.Dialect, ir.SemanticDigest})
	if err != nil {
		return nil, err
	}
	var out strings.Builder
	out.WriteString("// Code generated by gooo-semantic-migration-compiler; DO NOT EDIT.\n")
	out.WriteString("package " + packageName + "\n\n")
	out.WriteString("const SemanticBindingJSON = " + strconv.Quote(string(metadata)) + "\n")
	out.WriteString("const SemanticIRJSON = " + strconv.Quote(string(raw)) + "\n")
	return []byte(out.String()), nil
}

func ParseIR(raw []byte) (SemanticIR, error) {
	var ir SemanticIR
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&ir); err != nil {
		return SemanticIR{}, err
	}
	if ir.Schema != IRSchema || ir.SemanticDigest == "" || ir.SemanticDigest != ir.canonicalDigest() {
		return SemanticIR{}, errors.New("semantic IR identity or digest is invalid")
	}
	return ir, nil
}

func listValue(values []string) string {
	if len(values) == 0 {
		return "-"
	}
	return strings.Join(values, "|")
}

func executionFingerprint(source, target Execution) string {
	return DigestValue(struct {
		Source Execution `json:"source"`
		Target Execution `json:"target"`
	}{source, target})
}
